#pragma once

#include <stddef.h>

#define mBuiltin(function_name) int function_name (char *argv[])
typedef int (*BuiltinPtr)(char *argv[]);

mBuiltin(commands_echo);
mBuiltin(commands_printf);
mBuiltin(commands_exit);
mBuiltin(commands_pwd);
mBuiltin(commands_cd);

typedef struct {
    const char *name;
    BuiltinPtr function;
} BuiltinAndKey;

// This function is automatically generated by gperf. It is used to get the function for a builtin
// command given the command's name. If there's no builtin that matches the provided key, NULL is
// returned.
const BuiltinAndKey *getShellBuiltin(register const char *key, register size_t length);

